#ifndef _DCL_CONFIG_RELEASE_H_INCLUDED_
#define _DCL_CONFIG_RELEASE_H_INCLUDED_

#include "uc/logs/args.h"

#define DCL_LOG_TYPE_DEFAULT UC_LOG_TYPE_NONE
#define DCL_LOG_OPT_DEFAULT UC_LOG_OPT_TIME
#define DCL_LOG_PREFIX_DEFAULT "DCL(RELEASE)"

#endif
