#ifndef DCL_CONFIG_TRACE_H_INCLUDED
#define DCL_CONFIG_TRACE_H_INCLUDED

#include "uc/logs/args.h"

#define DCL_LOG_TYPE_DEFAULT UC_LOG_TYPE_INFO|UC_LOG_TYPE_WARN|UC_LOG_TYPE_ERR|UC_LOG_TYPE_DEBUG
#define DCL_LOG_OPT_DEFAULT UC_LOG_OPT_TIME
#define DCL_LOG_PREFIX_DEFAULT "DCL(TRACE)"

#endif
