#ifndef DCC_CONFIG_OUTPUT_H_INCLUDED
#define DCC_CONFIG_OUTPUT_H_INCLUDED

#include "uc/logs/args.h"

#define DCC_LOG_TYPE_DEFAULT UC_LOG_TYPE_INFO|UC_LOG_TYPE_WARN|UC_LOG_TYPE_ERR
#define DCC_LOG_OPT_DEFAULT UC_LOG_OPT_TIME
#define DCC_LOG_PREFIX_DEFAULT "DCC(OUTPUT)"

#endif
